### ISSUE TITLE
Info.plist issue, unable to version up 

### ISSUE THREAD

**Issue by theZulqarnain** [gustarus/react-native-version-up#16]
I have developed my ejected expo app from Mac, now I have shifted to Linux. I'm getting below error.

```
 node ./node_modules/react-native-version-up/index.js --patch 1.1.6
internal/fs/utils.js:259
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/zulqarnain/stanplus/stanclinic-2.0/ios/StanClinic/Info.plist'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.getBuildNumberFromPlist (/home/zulqarnain/stanplus/stanclinic-2.0/node_modules/react-native-version-up/lib/helpers.js:27:24)
    at Object.<anonymous> (/home/zulqarnain/stanplus/stanclinic-2.0/node_modules/react-native-version-up/index.js:30:30)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/zulqarnain/stanplus/stanclinic-2.0/ios/StanClinic/Info.plist'
}
error Command failed with exit code 1.
```
I Checked Info.plist its there in folder but showing error that directory not found. I'm able to generate APK but couldn't bump the version.

**Comment by dakkafex** [comment]
it looks like its using the name specified in your package.json file, but RN generates the folder names for iOS to pascal case where the package turns it to skewer case .

A fix would be just to follow that convention, im gonna give it a try

**Comment by dakkafex** [comment]
so just make sure there is no skewer-case in your package name and it should work fine, as the folders arent case sensitive or something
