### ISSUE TITLE
Git error on windows with Git Bash

### ISSUE THREAD

**Issue by ThaJay** [gustarus/react-native-version-up#6]
To start off, thank you for this very handy script. It's a very nice way to consistently up the versions of our app. It always worked nicely on Ubuntu, but now my laptop configuration has changed after a hardware upgrade an I develop our react-native app on Windows with Git Bash.

The error probably has something to do with mixing `/` `\` and `\\` in the paths, but I'm not sure how to work around this one. It did change the files properly of course, I just had to manually commit and tag because of this fault.

This is the full log from the cli:
```
$ yarn version-up --minor 
 
yarn run v1.15.2
$ node ./node_modules/react-native-version-up/index.js --minor    

I'm going to increase the version in:
  - package.json (C:\dev\project-name/package.json);
  - ios project (C:\dev\project-name/ios/appName/Info.plist);
  - android project (C:\dev\project-name/android/app/build.gradle).   

The version will be changed:
  - from: 2.3.7 (72);
  - to:   2.4.0 (73).

Use "2.4.0" as the next version? [y/n] y

Updating versions
  Updating version in package.json...
    Version in package.json changed.
  Updating version in xcode project...
    Version and build number in ios project (plist file) changed. 
  Updating version in android project...
    Version and build number in android project (gradle file) chan

ged.

I'm ready to cooperate with the git!
  I want to make a commit with message:
    "release 2.4.0: increase versions and build numbers"
  I want to add a tag:
    "v2.4.0"
  Do you allow me to do this? [y/n] y

Error: Command failed: git add C:\dev\project-name/package.json C:\dev

\project-name/ios/appName/Info.plist C:\dev\project-name/android/app/build.

gradle && git commit -m 'release 2.4.0: increase versions and buil

d numbers' && git tag -a v2.4.0 -m 'release 2.4.0: increase versio
 
ns and build numbers'
error: pathspec '2.4.0:' did not match any file(s) known to git   
error: pathspec 'increase' did not match any file(s) known to git 
error: pathspec 'versions' did not match any file(s) known to git 
error: pathspec 'and' did not match any file(s) known to git      
error: pathspec 'build' did not match any file(s) known to git    
error: pathspec 'numbers'' did not match any file(s) known to git 

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process

.js:267:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git add C:\\dev\\project-name/package.json ' +
    'C:\\dev\\project-name/ios/appName/Info.plist ' +
    "C:\\dev\\project-name/android/app/build.gradle && git commit -m '

release " +
    "2.4.0: increase versions and build numbers' && git tag -a v2.

4.0 " +
    "-m 'release 2.4.0: increase versions and build numbers'"     
}
Done in 4.81s.
```

**Comment by ThaJay** [comment]
My theory is that it would probably work if
```
git add C:\dev\project-name/package.json C:\dev\project-name/ios/appName/Info.plist C:\dev\project-name/android/app/build.gradle && git commit -m 'release 2.4.0: increase versions and build numbers' && git tag -a v2.4.0 -m 'release 2.4.0: increase versions and build numbers'
```
is changed to:
```
git add C:\dev\project-name/package.json C:\dev\project-name/ios/appName/Info.plist C:\dev\project-name/android/app/build.gradle
git commit -m 'release 2.4.0: increase versions and build numbers'
git tag -a v2.4.0 -m 'release 2.4.0: increase versions and build numbers'
```
The files are staged for commit correctly. The last && could even stay in because it purey chokes after the first && but why not give them all their own line.
